#!/usr/bin/env bash

set -e
#set -x

TMPDIR=$(mktemp -d)

trap "rm -rf $TMPDIR" EXIT

CI_VENV="$TMPDIR/.ci_venv"

# Avoid issues with building pillow as we install mingw-w64-x86_64-python-pillow
if [[ "$(uname -s)" =~ ^MINGW64_NT.* ]]; then
    CI_VENV_ARGS="--system-site-packages"
fi

python3 -m venv $CI_VENV_ARGS $CI_VENV
source $CI_VENV/bin/activate

# Install dependencies
python3 -m pip install -U pip wheel
python3 -m pip install .
python3 -m pip install --group dev

pytest -vv -m system --qmk=real
